name: CowPaths
main: com.ryanmichela.cowpaths.plugin.CowPaths
version: 2
website: https://github.com/rmichela/CowPaths
author: Ryan Michela
description: >
             Tracks player statistics and provides a web-based report.
